import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { Providers } from '@/state/store/providers';
import { LoadingProvider } from '@/ui/context/loading-provider';
import AppFooter from '@/ui/layout/footer';
import AppHeader from '@/ui/layout/header';

import { languages } from '../i18n/settings';
import './../globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'ChowShop',
	description: 'Generated by create next app',
	themeColor: '#09090b',
	manifest: 'https://expense.fyi/manifest.json',
	viewport: {
		width: 'device-width',
		initialScale: 1,
		userScalable: false,
	},
};
export async function generateStaticParams() {
	return languages.map((lng) => ({ lng }));
}
export default function RootLayout({ children, params }: { children: React.ReactNode; params: any }) {
	const { lng } = params;
	return (
		<html lang={lng}>
			<body className={inter.className}>
				<LoadingProvider>
					<Providers>
						<AppHeader />
						<div>{children}</div>
						<AppFooter />
					</Providers>
				</LoadingProvider>
			</body>
		</html>
	);
}
